apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: mongodb
        image: 288761756077.dkr.ecr.us-east-1.amazonaws.com/mongodb:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-logs
          mountPath: /var/log/mongodb
        command: ["mongod", "--logpath=/var/log/mongodb/mongod.log", "--logappend", "--bind_ip_all"]
      volumes:
      - name: mongo-data
        emptyDir: {}
      - name: mongo-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: LoadBalancer
