apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"  # Remplacez par votre email
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"  # Remplacez par un mot de passe fort
        resources:
          requests:
            memory: "128Mi"  # Demande de mémoire
            cpu: "250m"      # Demande de CPU
          limits:
            memory: "256Mi"  # Limite de mémoire
            cpu: "500m"      # Limite de CPU
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pgadmin
  type: LoadBalancer
